import type { Metadata } from "next";
import "./globals.scss";
import "../icons/icons.css";
import NextTopLoader from "nextjs-toploader";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap", // եթե ուզում ես ֆոլբեք ֆոնտ մինչ բեռնվելը
});

export const metadata: Metadata = {
  title: "VLKSM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hy" suppressHydrationWarning={true} className={inter.className}>
      <body className="h-[100dvh]">
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
